[package]
name = "cfgmk"
version = "0.1.0"
authors = ["Hank Donnay <hdonnay@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
readme = "README.md"

[dependencies]
nom = "^4.1"
structopt = "0.2"
tar = "0.4"
walkdir = "2"
